package frc.robot.commands;

//import java.util.Timer;

import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.subsystems.DriveTrain;
import edu.wpi.first.wpilibj.Timer;

public class AutoNav1 extends CommandBase{
private DriveTrain driveTrain;
private double left = 0.0;
private double right = 0.0;
private Timer timer;
    public AutoNav1(DriveTrain subsystem){
        this.driveTrain = subsystem;
        addRequirements(driveTrain);
        
    }

    @Override
    public void initialize() {
        timer = new Timer();
        timer.start();
        
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
               
        driveTrain.drive(0.0, 0.0);
        timer.delay(1.0);  
        
        
             
             
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
         return true;
           }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }

}